services:
  fido:
    build: .
    command: ["serve", "--port", "8080", "--config", "/root/.fido/config.yml"]
    volumes:
      - ~/.fido:/root/.fido
    ports:
      - "8080:8080"

  fido-daemon:
    build: .
    command: ["daemon", "--config", "/root/.fido/config.yml"]
    volumes:
      - ~/.fido:/root/.fido

  fido-web:
    build: ./web
    ports:
      - "3000:80"
    depends_on:
      - fido
